pipeline {
    agent {
        docker {
            image 'maven:3.8.6-openjdk-18-slim'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                script {
                    CI_ERROR = "Failed while building application"
                }                
                
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                script {
                    CI_ERROR = "Failed while running test"
                }                   
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                script {
                    CI_ERROR = "Failed while deploying application"
                }
                sh './jenkins/scripts/deliver.sh'
            }
        }       
    }

    
    // post {
    //     always {
    //         echo '====== Clean up workspace ======'
    //         deleteDir() /* clean up our workspace */
    //         echo '====== Workspace has been cleaned ======'
    //     }

    //     success {
    //         echo '====== Pipeline ran successfully ======'
    //         emailext to: 'bendy.chen@west.com',
    //             subject: "Successfully run Jenkins Pipeline: ${currentBuild.fullDisplayName}",
    //             body: "Build URL: ${env.BUILD_URL}"
            
    //         sendSlackNotifcation()
    //     }

    //     failure {
    //         echo '====== Pipeline failed ======'

    //         emailext to: 'bendy.chen@west.com',
    //             subject: "Failed Jenkins Pipeline: ${currentBuild.fullDisplayName}",
    //             body: "Something went wrong with ${env.BUILD_URL}, please check the Console Output for more details."
            
    //         sendSlackNotifcation()
    //     }
    // }
    post {
        always {
            script {
                CONSOLE_LOG = "${env.BUILD_URL}/console"
                BUILD_STATUS = currentBuild.currentResult
                if (currentBuild.currentResult == 'SUCCESS') {
                    CI_ERROR = "NA"
                }
            }

            sh """
                TODAY=`date +"%b %d"`
                sed -i "s/%%JOBNAME%%/${env.JOB_NAME}/g" jenkins/report.html
                sed -i "s/%%BUILDNO%%/${env.BUILD_NUMBER}/g" jenkins/report.html
                sed -i "s/%%DATE%%/\${TODAY}/g" jenkins/report.html
                sed -i "s/%%BUILD_STATUS%%/${BUILD_STATUS}/g" jenkins/report.html
                sed -i "s/%%ERROR%%/${CI_ERROR}/g" jenkins/report.html
                sed -i "s|%%CONSOLE_LOG%%|${CONSOLE_LOG}|g" jenkins/report.html
            """

            publishHTML(target:[
                allowMissing: true,
                alwaysLinkToLastBuild: true, 
                keepAll: true, 
                reportDir: "${WORKSPACE}/jenkins", 
                reportFiles: 'report.html', 
                reportName: 'CI-Build-HTML-Report', 
                reportTitles: 'CI-Build-HTML-Report'
            ])

            sendSlackNotifcation()
        }
    }
}

def sendSlackNotifcation()
{
    if ( currentBuild.currentResult == "SUCCESS" ) {
        buildSummary = "Job: ${env.JOB_NAME}\n Status: *SUCCESS*\n Build Report: ${env.BUILD_URL}CI-Build-HTML-Report"
        slackSend color : "good", message: "${buildSummary}", channel: 'cma-app-builder'
    }
    else {
        buildSummary = "Job: ${env.JOB_NAME}\n Status: *FAILURE*\n Error description: *${CI_ERROR}* \nBuild Report :${env.BUILD_URL}CI-Build-HTML-Report"
        slackSend color : "danger", message: "${buildSummary}", channel: 'cma-app-builder'
    }
}
